language: java
jdk:
  - oraclejdk8
  - oraclejdk9
addons:
  apt:
    packages:
      - jq
env:
  global:
    - GH_REF: github.com/sosy-lab/common-java.git
install:
  - ant resolve-dependencies
matrix:
  include:
    - env: NAME='Build with ECJ'
      script:
        - ant build-project-ecj
    - env: NAME='Unit Tests'
      script:
        - ant unit-tests-coverage
    - env: NAME='Create Javadoc'
      script:
        - ant javadoc
    - env: NAME=Checkstyle
      script:
        - ant run-checkstyle -Dcheckstyle.output=plain && cat Checkstyle*.xml && [ $(cat Checkstyle*.xml | grep -vic audit) -eq 0 ]
    - env: NAME=FindBugs
      script:
        - ant run-findbugs -Dfindbugs.output=text && cat FindBugs.xml && test \! -s FindBugs.xml
    - env: NAME='Check source-code format'
      script:
        - ant format-source && git diff -s --exit-code
deploy:
  - skip_cleanup: true
    provider: script
    script: build/deploy-gh-pages.sh
    on:
      condition: $NAME = "Create Javadoc"
  - skip_cleanup: true
    provider: script
    script: build/deploy-coverage.sh
    on:
      condition: $NAME = "Unit Tests"
notifications:
  email:
    - common-java-dev@googlegroups.com
git:
  depth: 1
cache:
  directories:
  - $HOME/.ivy2
